RD /S /Q .vs
RD /S /Q bin
RD /S /Q obj
RD /S /Q BlazorAuthentication\Client\bin
RD /S /Q BlazorAuthentication\Client\obj
RD /S /Q BlazorAuthentication\Server\bin
RD /S /Q BlazorAuthentication\Server\obj
RD /S /Q BlazorAuthentication\Shared\bin
RD /S /Q BlazorAuthentication\Shared\obj
RD /S /Q ModelingSystem\Client\bin
RD /S /Q ModelingSystem\Client\obj
RD /S /Q ModelingSystem\Server\bin
RD /S /Q ModelingSystem\Server\obj
RD /S /Q ModelingSystem\Shared\bin
RD /S /Q ModelingSystem\Shared\obj
