version: '3.7'

services:
  modelingsystem.server:
    image: ${DOCKER_REGISTRY-}modelingsystemserver
    build:
      context: .
      dockerfile: ModelingSystem/Server/Dockerfile


##########################################################        
############## Docker NETWORKS configuration #############
##########################################################
networks:
  traefik:
    driver: overlay
    name: traefik
  inbound:
    driver: overlay
    name: inbound